### PR TITLE
#1 added media queries for mobile responsiveness

### PR DESCRIPTION
**Pull request by Davethadev**
Hello. So I'm done with the task and the website now looks good on mobile. I published it on my github pages so here's the link to view it and see how it looks now
https://davethadev.github.io/Our-Forgotten-Heros/
I'd appreciate any feedback or comments on my work and if you're satisfied with the changes, you could merge my pr. Thank you

### CODE REVIEW

**Comment by mkgupta01** [comment]
Thanks for your contribution.
Will review it by tomorrow.

Mention the issue this PR is related to that's a good practice.

**Comment by Davethadev** [comment]
Alright thanks for the feedback. I didn't know I had to mention the issue the pr is related to. Thanks for letting me know it's good practice to do so. I've tried since then to do just that but I can't seem to figure it out. I'd appreciate if you could put me through on that. Thanks

**Comment by mkgupta01** [comment]
Just add the issue number like #1 in the PR description

**Comment by Davethadev** [comment]
Alright will do that now

**Comment by mkgupta01** [comment]
You have made only the Home page responsive, other pages needs also to be made responsive

image

**Comment by Davethadev** [comment]
I think the other pages are responsive the way they are. The only problem with them is that they've not been given adequate styling to make them look good unlike the home page. I don't think I can do much more for them with regards to responsiveness

**Comment by mkgupta01** [comment]
I need all the pages to be responsive. I you want I can close this PR

**Pull request closed without merging**
